const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
class Node{constructor(){this.children=[];this.style={};this.attrs={};this.listeners={};this.open=false}setAttribute(k,v){this.attrs[k]=v}removeAttribute(k){delete this.attrs[k]}append(...a){this.children.push(...a)}replaceChildren(){this.children=[]}addEventListener(k,f){this.listeners[k]=f}querySelector(k){return this.parts[k]}showModal(){this.open=true}close(){this.open=false;this.listeners.close?.()}focus(){}}
const parts={};for(const key of ['.shared-bag-items','.shared-bag-footer strong','.shared-bag-footer a','[role="status"]','[data-bag-close]'])parts[key]=new Node();const dialog=new Node();dialog.parts=parts;
const body=new Node(),events={},handlers={},storage=new Map([['lvl-cart-discs',JSON.stringify(['one','one','hidden'])]]);
const document={body,documentElement:new Node(),activeElement:new Node(),createElement:tag=>tag==='dialog'?dialog:new Node(),addEventListener:(n,f)=>events[n]=f,dispatchEvent(){},getElementById(){return null}};
const window={SITE_CONTENT:{settings:{whatsappNumber:'593 123'},records:[{id:'one',stock:1,title:'Disc',artist:'Artist',price:28},{id:'hidden',stock:2,hideFromPublic:true}]},addEventListener:(n,f)=>handlers[n]=f,scrollY:42,scrollTo(){}};
vm.runInNewContext(fs.readFileSync('bag.js','utf8'),{document,window,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},URLSearchParams,location:{search:''},Event:class{},Map,Number,String,Math,JSON});
assert.deepEqual(JSON.parse(storage.get('lvl-cart-discs')),['one']);assert.match(parts['.shared-bag-footer a'].href,/wa.me\/593123\?/);
const trigger={id:'',dataset:{add:'one'},hasAttribute:k=>k==='data-add'};events.click({target:{closest:()=>trigger},preventDefault(){},stopImmediatePropagation(){}});assert.equal(dialog.open,true);assert.equal(JSON.parse(storage.get('lvl-cart-discs')).length,1);assert.equal(body.style.position,'fixed');dialog.close();assert.equal(body.style.position,undefined);
const controls=parts['.shared-bag-items'].children[0].children[1];assert.equal(controls.children[2].disabled,true);controls.children[0].onclick();assert.deepEqual(JSON.parse(storage.get('lvl-cart-discs')),[]);assert.equal(parts['.shared-bag-footer a'].attrs['aria-disabled'],'true');
storage.set('lvl-cart-discs','["one"]');handlers.pageshow();assert.equal(parts['.shared-bag-footer a'].attrs['aria-disabled'],'false');console.log('PASS: stock limits, hidden items, checkout recipient, empty checkout, scroll lock and page-return refresh');
