const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../discos.js'),'utf8');
function node(){return {dataset:{},style:{setProperty(){}},classList:{remove(){},add(){}},setAttribute(k,v){this[k]=v},focus(){},querySelector(){return node()}}}
const sheet=node(),opener=node();
const context={window:{innerHeight:800},iosSheet:sheet,sheetPosition:'compact',document:{body:node(),querySelector:()=>opener},requestAnimationFrame:f=>f(),syncDeckTimeline(){},setTimeout:f=>f()};
vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function sheetHeights()'),source.indexOf("document.querySelectorAll('[data-disc-view]')")),context);
context.setSheetPosition('compact');assert.equal(sheet.inert,true);
context.openIosPlayer();assert.equal(sheet.dataset.position,'expanded');assert.equal(sheet.style.height,'738px');assert.equal(sheet.inert,false);assert.equal(opener['aria-expanded'],'true');
assert.deepEqual(Object.keys(context.sheetHeights()),['compact','expanded']);
const handlers={};context.wireSheetDrag({addEventListener:(name,fn,capture)=>{handlers[name+(capture?'Capture':'')]=fn},setPointerCapture(){}});
handlers.pointerdown({button:0,clientY:100,pointerId:1});handlers.pointermove({clientY:600});assert.equal(sheet.style.height,'238px');handlers.pointerup({clientY:600});assert.equal(sheet.dataset.position,'compact');assert.equal(sheet.inert,true);
context.setSheetPosition('expanded');handlers.pointerdown({button:0,clientY:300,pointerId:3});handlers.pointermove({clientY:450});handlers.pointercancel();assert.equal(sheet.style.height,'738px');
context.window.innerHeight=390;context.setSheetPosition('expanded');assert.equal(sheet.style.height,'328px');
const a={id:'a'},b={id:'b'},c={id:'c'};let mounts=0,plays=0,info=[];
Object.assign(context,{records:[a,b,c],selected:a,pendingRecord:a,document:{baseURI:'https://example.test/'},updateSelectedInfo(r,preview){context.pendingRecord=r;info.push({r,preview})},audioUrl:r=>r===c?'':'audio.mp3',mountRecord(r){mounts++;context.selected=r;context.pendingRecord=r},togglePlayback(){plays++}});
vm.runInContext(source.slice(source.indexOf('function browseIosRecord('),source.indexOf('function updateSelectedInfo(')),context);
context.browseIosRecord(b,false);assert.equal(context.selected,a);assert.equal(mounts,0);assert.equal(plays,0);assert.equal(info[0].preview,true);
context.playBrowsedRecord();assert.equal(context.selected,b);assert.equal(mounts,1);assert.equal(plays,1);
context.playBrowsedRecord();assert.equal(mounts,1);assert.equal(plays,2);
context.browseIosRecord(c,false);context.playBrowsedRecord();assert.equal(mounts,1);assert.equal(plays,2);
console.log('PASS: two positions, drag snapping, cancellation, viewport resize, browsing preserves playback, Play commits selection, unavailable preview does not interrupt');
